name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          npm install -g browserify
          npm install regexp-tree
      - name: Bundle
        run: |
          mkdir -p page/dist
          browserify worker.js -o page/dist/bundle.js
          mv *.html favicon.png main.js main.css page
      - name: Set up Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'page'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
